
## Research Objective

<<<<<<< HEAD
The primary research goal was to evaluate the Reinforcement Learning-based algorithm for multiasset trading.
The main idea behind the algorithm deployment is that it can systematically outperform benchmarks 
in terms of selected risk and return measures. 
Designed trading system was aimed to spot non-trivial patterns in data, more efficiently than human, and exploit them accordingly.

In the project author wanted to assess the possibility of using a reinforcement learning agent for
trading domain. The objectives are as follows:

* Implementation - consisting of creating reinforcement learning-based agent that are capable of trading financial instruments 
basing on time series tables
* Evaluation - testing if trading agents for out-of-sample periods can outperform benchmarks in the measures provided by the author
* Conclusion - answering the question if such approach might help in generating abnormal positive results and determining if the method can 
be feasible and efficient in real-like environment

=======
The primary research goal is to evaluate the Reinforcement Learning-based algorithm for multiasset trading.
The main idea behind the algorithm deployment is that it can systematically outperform benchmarks 
in terms of both risk and return. 
The trading system will be able to spot non-trivial patterns, faster than human, and exploit them.
Research will
The goal of this project is to assess the possibility of using Reinforcement Learn-
ing to create a trading agent which is capable of nding persistent similarities in 
nancial time series and which learns how to dene and exploit deviations from
the expected, prevalent behaviour. We design and compare two approaches, a basic
approach based on Monte Carlo Control and an extended approach based on Qlearn-
ing and value function approximation. The rst approach is aimed to provide more
interpretability, the second approach is to provide better performance. We assess
the outcome by the trading performance of the two agents on two weeks of out-of-
sample fx market test data with one minute granulation. We set two benchmarks by
which we measure trading performance. The percentage return and the Sharpe ratio
of the trades the agent engages in should be higher than the return of a buy-and-
hold strategy of either of the underlying cointegrated assets. A secondary goal is
to draw conclusions about the interactions in parameter settings of the pair trading
frame work and how they in
uence protability of the pair trade. The objectives
are summarized in the following list:
The objectives are as follows:

Design and deployment - this part 
>>>>>>> 4c974038f5aca0a810f99d5338597bc1f56dba40



