data:
  feature_config: src/configs/features/hft_lob_features_all.yaml
env:
  mode: hft
  feature_columns:
  - feature_hft_book_pressure_l0
  - feature_hft_book_pressure_l1
  - feature_hft_book_pressure_l2
  - feature_hft_book_pressure_l3
  - feature_hft_book_pressure_l4
  - feature_hft_microprice
  - feature_hft_microprice_divergence
  - feature_hft_spread_bps
  - feature_hft_order_book_imbalance_5l
  - feature_hft_depth_ratio
  - feature_hft_vwmp_skew_5l
  - feature_hft_bid_slope
  - feature_hft_ask_slope
  - feature_hft_bid_px_00
  - feature_hft_ask_px_00
  - feature_hft_bid_sz_00
  - feature_hft_ask_sz_00
  - feature_hft_bid_px_01
  - feature_hft_ask_px_01
  - feature_hft_bid_sz_01
  - feature_hft_ask_sz_01
  - feature_hft_bid_px_02
  - feature_hft_ask_px_02
  - feature_hft_bid_sz_02
  - feature_hft_ask_sz_02
  - feature_hft_bid_px_03
  - feature_hft_ask_px_03
  - feature_hft_bid_sz_03
  - feature_hft_ask_sz_03
  - feature_hft_bid_px_04
  - feature_hft_ask_px_04
  - feature_hft_bid_sz_04
  - feature_hft_ask_sz_04
