data:
  feature_config: src/configs/feature_sets/hft_lob_features_all.yaml
env:
  mode: hft
  feature_columns:
  - feature_hft_book_pressure_l0
  - feature_hft_order_book_imbalance_3l
  - feature_hft_order_count_imbalance_l0
  - feature_hft_microprice
  - feature_hft_microprice_divergence
  - feature_hft_bid_slope
  - feature_hft_ask_slope
  - feature_hft_ofi
  - feature_hft_ofi_rolling_50
  - feature_hft_signed_trade_flow_50
  - feature_position
