# ---
# title: "Master's thesis"
# author: "Krzysztof Wojdalski (310284)"
# date:  "`r format(Sys.time(), '%Y-%m-%d')`"
# output: pdf_document
# ---

The following chapter introduces articles that correspond with the subject of the current thesis and are considered as fundamentals of modern finance.
Specifically, the beginning contains financial market models. The next subchapter includes basic investment effectiveness indicators that implicitly or explicitly result from the fundamental formulas from the first subchapter.

## Selected financial market models

Works considered as a fundament of quantitative finance and investments are Sharpe, Lintner, and Mossin. All there authors, almost simultaneously, formulated Capital Asset Pricing Model (CAPM) that describes dependability between rate of return and its risk, risk of the market portfolio, and risk premium.
Assumptions in the model are as follows:
Decisions in the model regards only one period
Market participants has risk aversion, i.e. their utility function is related with plus sign to rate of return, and negatively to variance of portfolio rate of return
Risk free rate exists
asymmetry of information non-existment
Lack of speculative transaction
Lack of transactional costs, taxes included
Market participants can buy a fraction of the asset
Both sides are price takers
Short selling exists

Described by the following model formula is as follows

$$
\E(R_P)=R_F+frac{\sigma_P/\sigma_M ×[E(R_M)-R_F]
$$
	
gdzie:
E(R_P ) – oczekiwana stopa zwrotu z portfela,
E(R_M) – oczekiwana stopa zwrotu z portfela rynkowego,
R_F – stopa zwrotu wolna od ryzyka,
σ_P – odchylenie standardowe stóp zwrotu z portfela,
σ_M – odchylenie standardowe stóp zwrotu z portfela rynkowego.
Funkcja 〖E(R〗_P) to tzw. Capital Market Line (CML). Każdy z portfeli znajdujący się na tej linii jest efektywny. Oznacza to, że stopa zwrotu z niego jest proporcjonalna do podejmowanego ryzyka.
Kolejny ze wzorów uwzględnia wszystkie portfele, także pojedynczych akcji. Wiąże się to z tzw. SML (Security Market Line) i dane jest jako następujące równanie:
	E(R_i )=R_F+β_i×[E(R_M)-R_F]	( 14 )
gdzie: 
〖E(R 〗_i) – oczekiwana stopa zwrotu z i-tego portfela,
〖E(R〗_M) – stopa zwrotu z portfela rynkowego,
R_F – oczekiwana stopa zwrotu wolna od ryzyka,
β_i – współczynnik beta.
	Wybrane artykuły dotyczące miar efektywności inwestycji
Przedstawione artykuły nie obejmują żadnej miary, która mierzyłaby efektywność zarządzania portfelem. Wynikające z nich równania są jednak istotne, gdyż część później wprowadzonych wskaźników opiera się właśnie o model CAPM. Najbardziej znane z nich to wskaźnik Sharpe’a, wskaźnik Treynora i Alfa Jensena. Są to proste narzędzia, które przytacza się w mediach dla masowego odbiorcy i zrozumiałe dla przeciętnego inwestora (Marte, 2012). Na ich podstawie porównuje się efektywność portfeli inwestycyjnych, w tym również tych zarządzanych przez menedżerów funduszy inwestycyjnych.
W pracy Sharpe’a (1966) wprowadzony został wskaźnik R/V, znany jako wskaźnik Sharpe’a (S), który dany jest wzorem:
	S_i=(E(R_i-R_F))/σ_i 	( 15 )
gdzie: 
〖R 〗_i –stopa zwrotu z i-tego portfela,
R_F –stopa zwrotu wolna od ryzyka,
σ_i – odchylenie standardowe stóp zwrotu z i-tego portfela.
W pracy Treynora (1965) został zaproponowany miernik, w którym mianownik zawiera β_i zamiast σ_i. Omawiana formuła dana jest za pomocą poniższej formuły:
	T=(R_i-R_F)/β_i 	( 16 )
gdzie: 
〖R 〗_i – stopa zwrotu z i-tego portfela,
R_F – stopa zwrotu wolna od ryzyka,
β_i – współczynnik beta i-tego portfela.
Oba przytoczone wskaźniki (S i T) są to miary względne. Ich wartości należy porównać z benchmarkiem, by stwierdzić, czy dane portfolio było dobrze zarządzany. Jeżeli są one większe (mniejsze), to oznacza to, że analizowane jednostki były lepsze (gorsze) niż wzorcowy portfel.
Ostatnia miara, szczególnie popularna wśród uczestników rynku finansowego, to tzw. Alfa Jensena. Jest ona dana za pomocą równania ( 17 ).
	α_i=R_i-[R_F+β_i×(R_M-R_F )]	( 17 )
gdzie: 
〖R 〗_i – stopa zwrotu z i-tego portfela,
R_F – stopa zwrotu wolna od ryzyka,
β_i – współczynnik beta i-tego portfela.
Alfa Jensena jest miarą bezwzględną. Liczy się ją jako różnicę między rzeczywistą a implikowaną przez model stopą zwrotu, liczoną jako różnicą pomiędzy rzeczywistą stopą zwrotu z badanego portfela a teoretyczną stopą zwrotu, którą determinuje model CAPM. Im wartość tego wskaźnika jest większa, tym lepiej dla badanej obserwacji.
	Teoria portfelowa Markowitza
W poniższej części zostanie omówiona teoria portfelowa Markowitza (1952), o którą opiera się badanie empiryczne z kolejnego rozdziału. Powstanie MPT (modern portfolio theory) jest datowane na rok 1952, kiedy to w czasopiśmie Journal of Finance została opublikowana praca pt. Portfolio Selectio. Henry Markowitz stworzył model, w którym kryterium inwestycyjnym, oprócz stopy zwrotu, było ryzyko. Autor dostrzegł, że przy odpowiednim doborze składników w portfelu oraz poprzez ustalanie różnych wag w portfelu można uzyskać dwa portfele o równym poziomie zysku, lecz różnym poziomie wariancji stopy zwrotu. Redukcja ryzyka jest możliwa, poprzez odpowiednią dywersyfikację, czyli zróżnicowanie walorów w portfelu (np. zakup obligacji, akcji i surowców). Zmienność stóp zwrotu całego portfolia może zostać ograniczona za pomocą analizy wzajemnego wpływu poszczególnych składników w portfolio. Dokonuje się tego za pomocą narzędzi znanych ze statystyki oraz algebry liniowej (macierzy kowariancji i macierzy korelacji). Należy zaznaczyć, że większa liczba aktywów w portfelu zawsze będzie redukowała minimalny poziom ryzyka portfela, jednak to od stopnia korelacji między aktywami zależy siła tej niwelacji. 
Teoria Markowitza determinuje to, że dla każdej założonej stopy zwrotu istnieje tylko i wyłącznie jeden portfel, który minimalizuje ryzyko. Alternatywnie – istnieje tylko i wyłącznie jeden portfel, który dla danego poziomu ryzyka maksymalizuje oczekiwaną stopę zwrotu. Istotnym terminem, który pojawia się w literaturze przedmiotu, to tak zwany portfel efektywny, czyli taki, dla którego nie da się znaleźć wyższej oczekiwanej stopy zwrotu (niższej wariancji) przy danym oczekiwanym poziomie wariancji (stopy zwrotu). 
Należy dodać, że opisywana koncepcja Markowitza jest determinowana założeniem o awersji przeciętnego inwestora giełdowego wobec ryzyka, wyrażoną za pomocą
równania ( 18 ):
	E(U)<U(E(X))	( 18 )
gdzie:
E(U) – wartość oczekiwana użyteczności z wypłaty;
U(E(X)) – użyteczność wartości oczekiwanej wypłaty.
Wartość oczekiwana użyteczności z wypłaty dana jest za pomocą wzoru:
	E(U)=∑_(i=1)^n▒〖π_i U(c_i)〗	( 19 )
gdzie:
π_i – prawdopodobieństwo zaistnienia wypłaty c_i,
U(c_i) – użyteczność z wypłaty c_i.
Analiza portfelowa oprócz zalet (m.in. relatywnie prostej konstrukcji), posiada również wady. Przede wszystkim wynikają one z faktu, że model Markowitza służy do analizy danych historycznych, których zastosowanie może być problematyczne. Przeszłość nie musi odzwierciedlać tego, co zdarzy się na rynkach finansowych w przyszłości. Jeżeli na przykład dany podmiot przebranżawia się i ze spółki telekomunikacyjnej zmienia się w spółkę surowcową, to będzie miało to skutki w ryzyku, oczekiwanej stopie zwrotu i korelacji jej akcji z resztą aktywów dostępnych na rynku. Optymalny portfel z analizy ex post może więc zupełnie nie odnosić się do rzeczywistego ryzyka inwestycyjnego. Ponadto wyniki zastosowania teorii Markowitza mogą być bardzo wrażliwe na dobraną próbę. Im ilość obserwacji, dla których liczona są optymalne portfele, jest mniejsza, tym wrażliwość wyników jest większa. Przykład tej właściwości znajduje się na Rycinie 1.
