seed: 42
data:
  data_path: ./data/raw/synthetic/sine_wave_hft_lob.parquet
  data_config: src/configs/data/sine_wave_hft_lob.yaml
  download_data: false
  train_size: 2000
  validation_size: 10000
  feature_config: "src/configs/feature_sets/hft_lob_raw_passthrough.yaml"
  filter_lob_levels: 5
  feature_cache_dir: .cache/feature_transformation
env:
  backend: tradingenv
  mode: hft
  trading_fees: 0.0
  price_column: close
  include_position_feature: true
  obs_clip: 5.0
  reward_type: differential_sharpe
  reward_eta: 0.01
network:
  actor_hidden_dims:
  - 128
  - 64
  value_hidden_dims:
  - 128
  - 64
training:
  algorithm: TD3
  actor_lr: 0.0001
  value_lr: 0.0001
  value_weight_decay: 2.0e-06
  actor_weight_decay: 2.0e-06
  max_steps: 500000
  init_rand_steps: 5000
  frames_per_batch: 200
  optim_steps_per_batch: 5
  sample_size: 128
  buffer_size: 50000
  gamma: 0.99
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.3
  policy_delay: 2
  delay_actor: true
  delay_qvalue: true
  exploration_noise_std: 0.4
  loss_function: smooth_l1
  eval_steps: 10000
  eval_interval: 1000
  temp_eval_interval: 100000
  log_interval: 100
logging:
  log_level: INFO
  save_plots: false
