#!/usr/bin/env python3
"""Sync DSH skills from canonical Claude skills and agents.

Sources (canonical):
  .claude/skills/<name>/skill.md  -> .dsh/skills/<name>/SKILL.md
  .claude/agents/<name>.md        -> .dsh/skills/<name>/SKILL.md (inlined, self-contained)

Frontmatter is normalized to what DSH requires (name + description); Claude-only
fields (context, version, tags, author, license, compatible_tools) are dropped.

User-level skills in ~/.dsh/skills are NOT touched here; they sync from
~/dotfiles/claude, which is that repository's concern.

Usage:
  uv run scripts/sync_dsh_skills.py          # write .dsh/skills
  uv run scripts/sync_dsh_skills.py --check  # exit 1 if .dsh/skills is stale
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_SKILLS = REPO_ROOT / ".claude" / "skills"
SOURCE_AGENTS = REPO_ROOT / ".claude" / "agents"
DEST = REPO_ROOT / ".dsh" / "skills"

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)
NAME_RE = re.compile(r"[a-z0-9]+(-[a-z0-9]+)*")

# Frontmatter keys DSH understands; anything else is Claude-specific noise.
KEEP_KEYS = {"name", "description", "whenToUse"}


def parse_skill(path: Path) -> tuple[dict[str, str], str]:
    """Split a markdown file into frontmatter dict and body."""
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    frontmatter: dict[str, str] = {}
    for line in match.group(1).splitlines():
        kv = re.match(r"([\w-]+):\s*(.*)", line)
        if kv:
            frontmatter[kv.group(1)] = kv.group(2).strip().strip('"').strip("'")
    return frontmatter, text[match.end() :]


def render(name: str, description: str, body: str, provenance: str) -> str:
    header = f'---\nname: {name}\ndescription: "{description.replace(chr(34), chr(39))}"\n---\n\n'
    note = (
        f"<!-- Generated by scripts/sync_dsh_skills.py from {provenance}. "
        "Do not edit directly; edit the source and re-run the sync. -->\n\n"
    )
    return header + note + body.strip() + "\n"


def collect() -> dict[str, tuple[str, str]]:
    """Map destination skill name -> (rendered content, provenance)."""
    skills: dict[str, tuple[str, str]] = {}

    for path in sorted(SOURCE_SKILLS.glob("*/skill.md")):
        frontmatter, body = parse_skill(path)
        name = frontmatter.get("name") or path.parent.name
        if not NAME_RE.fullmatch(name):
            sys.exit(f"error: invalid kebab-case name {name!r} in {path}")
        description = frontmatter.get("description") or ""
        if not description:
            sys.exit(f"error: missing description in {path}")
        skills[name] = (
            render(name, description, body, f".claude/skills/{name}"),
            f".claude/skills/{name}",
        )

    for path in sorted(SOURCE_AGENTS.glob("*.md")):
        frontmatter, body = parse_skill(path)
        name = frontmatter.get("name") or path.stem
        if not NAME_RE.fullmatch(name):
            sys.exit(f"error: invalid kebab-case name {name!r} in {path}")
        description = (
            frontmatter.get("description")
            or f"Specialist agent for {path.stem.replace('-', ' ')} in this repository."
        )
        skills[name] = (
            render(name, description, body, f".claude/agents/{path.name}"),
            f".claude/agents/{path.name}",
        )

    return skills


def sync(check_only: bool) -> int:
    skills = collect()

    stale: list[str] = []
    missing = (
        set(skills) - {p.name for p in DEST.iterdir() if p.is_dir()}
        if DEST.exists()
        else set(skills)
    )

    for name, (content, _) in skills.items():
        target = DEST / name / "SKILL.md"
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            stale.append(name)

    if check_only:
        problems = stale + sorted(missing)
        if problems:
            print(
                "stale skills (run scripts/sync_dsh_skills.py): " + ", ".join(problems)
            )
            return 1
        print(f"ok: {len(skills)} skills up to date")
        return 0

    if DEST.exists():
        shutil.rmtree(DEST)
    for name, (content, _) in skills.items():
        skill_dir = DEST / name
        skill_dir.mkdir(parents=True)
        (skill_dir / "SKILL.md").write_text(content, encoding="utf-8")
    print(f"wrote {len(skills)} skills to {DEST}")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify .dsh/skills matches sources; exit 1 if stale",
    )
    args = parser.parse_args()
    raise SystemExit(sync(check_only=args.check))


if __name__ == "__main__":
    main()
