data:
  feature_config: src/configs/features/hft_lob_features_all.yaml
env:
  mode: hft
  feature_columns:
  - feature_hft_book_pressure_l0
  - feature_hft_book_pressure_l1
  - feature_hft_book_pressure_l2
  - feature_hft_order_book_imbalance_3l
  - feature_hft_order_count_imbalance_l0
  - feature_hft_microprice
  - feature_hft_microprice_divergence
  - feature_hft_vwmp_skew
  - feature_hft_spread_bps
  - feature_hft_spread_ratio_50
  - feature_hft_bid_convexity
  - feature_hft_ask_convexity
  - feature_hft_bid_slope
  - feature_hft_ask_slope
  - feature_hft_ofi
  - feature_hft_ofi_rolling_50
  - feature_hft_bid_queue_depletion
  - feature_hft_ask_queue_depletion
  - feature_hft_signed_trade_flow_50
  - feature_hft_odd_lot_trade_ratio_200
  - feature_hft_odd_lot_imbalance_200
  - feature_hft_inter_event_time
  - feature_hft_mid_price_acceleration
  - feature_hft_hour_sin
  - feature_hft_hour_cos
  - feature_position
